export const project = [
  {
    id: 0,
    title: "E-Commerce",
    desc: "Part of university final project. Created a UI for a E-Commerce application. The app contains features like integrated payment, recommendation and comprehensive detail.",
    thumbnail: "/project/thumbnail/ECommerce.webp",
    url: "https://www.figma.com/proto/bij8OTQPuLDjDyLsDVeNHv/HCI---Project?page-id=0%3A1&type=design&node-id=7-2&viewport=405%2C460%2C0.1&t=CcW2mXRwhCLusWs4-1&scaling=scale-down&starting-point-node-id=7%3A2&mode=design",
    source: "Figma",
    sourceurl:
      "https://www.figma.com/file/bij8OTQPuLDjDyLsDVeNHv/HCI---Project?type=design&node-id=0%3A1&mode=design&t=mosRZ5ZIb083OhTC-1",
  },
  {
    id: 1,
    title: "Wedding Planner",
    desc: "Part of university exam. Created a UI for a wedding place. The app can help users search, book, and pay for the place of their wedding.",
    thumbnail: "/project/thumbnail/Wedding Planner.webp",
    url: "https://www.figma.com/proto/tZ1g8qfiOXy4oYlyzwFPLr/HCI---Mid-Exam?page-id=0%3A1&type=design&node-id=2-40&viewport=294%2C568%2C0.47&t=2hrk8OTbLjy3ofxQ-1&scaling=scale-down&starting-point-node-id=2%3A40&mode=design",
    source: "Figma",
    sourceurl:
      "https://www.figma.com/file/tZ1g8qfiOXy4oYlyzwFPLr/HCI---Mid-Exam?type=design&node-id=0%3A1&mode=design&t=hhIiCalCCuqud4Y0-1",
  },
  {
    id: 2,
    title: "Tourism App",
    desc: "Part of university exam. Created a UI for an app to promote a tourism in Komodo Island, East Nusa Tenggara. The app contains features like emergency notification, place recommendation, guidelines, and general information.",
    thumbnail: "/project/thumbnail/Tourism.webp",
    url: "https://www.figma.com/proto/yvdpsRxRriroCLBme1aMEq/HCI---Final-Exam-2?page-id=2%3A2&type=design&node-id=4-24&viewport=589%2C294%2C0.09&t=A3L94ZgtCx0jDe3n-1&scaling=scale-down&starting-point-node-id=4%3A24&mode=design",
    source: "Figma",
    sourceurl:
      "https://www.figma.com/file/yvdpsRxRriroCLBme1aMEq/HCI---Final-Exam-2?type=design&node-id=2%3A2&mode=design&t=udRyIo2NUwXqWOdV-1",
  },
  {
    id: 3,
    title: "NOKA",
    desc: "Part of university project. Created a website for a game launch event. Contain information about the launch date, future plan and esports. built with <b>HTML</b> and <b>CSS.</b>",
    thumbnail: "/project/thumbnail/NOKA.webp",
    url: "https://noka.raflimalik.com",
    source: "Github",
    sourceurl: "https://github.com/RMalik777/HCI_Project.git",
  },
  {
    id: 4,
    title: "Astronom",
    desc: "Part of university project. Created a space themed website. Containing information and images from Hubble Space Telescope. Built with <b>HTML</b> and <b>CSS.</b>",
    thumbnail: "/project/thumbnail/astronom.webp",
    url: "https://astronom.raflimalik.com",
    source: "Github",
    sourceurl: "https://github.com/RMalik777/Astronom.git",
  },
  {
    id: 5,
    title: "KpopZtation",
    desc: "Part of university final project. Created a website for a music album shopping. Built with <b>ASP.NET</b> and <b>SQL Server.</b>",
    thumbnail: "/project/thumbnail/kpopztation.webp",
    url: "",
    source: "Github",
    sourceurl: "https://github.com/RMalik777/PSD_Lab.git",
  },
  {
    id: 6,
    title: "Mini Portfolio",
    desc: "Part of Bina Nusantara Computer Club mid project. Created a website for a personal portfolio. Built with <b>HTML, CSS</b>, and <b>JavaScript.</b>",
    thumbnail: "/project/thumbnail/miniporto.webp",
    url: "https://miniporto.raflimalik.com",
    source: "Github",
    sourceurl: "https://github.com/RMalik777/BNCC-Mid-Project.git",
  },
  {
    id: 7,
    title: "Tech Event Website",
    desc: "Part of Bina Nusantara Computer Club final project. Created a mockup website for a tech event called “Pudding Fest” by PT Musang. Created using <b>HTML, CSS, Bootstrap, JavaScript with jQuery</b>, and connected to Firebase <b>Firestore database.</b>",
    thumbnail: "/project/thumbnail/puddingfest.webp",
    url: "https://puddingfest.raflimalik.com",
    source: "Github",
    sourceurl: "https://github.com/RMalik777/BNCC-Final-Project.git",
  },
  {
    id: 8,
    title: "Link Book",
    desc: "Self created linktree alternative to host my social media links. Built with <b>SvelteKit</b> and <b>Tailwind CSS.</b>",
    thumbnail: "/project/thumbnail/linkbook.webp",
    url: "https://link.raflimalik.com",
    source: "Github",
    sourceurl: "https://github.com/RMalik777/LinkBook",
  },
  {
    id: 9,
    title: "Blog Website",
    desc: "A blog website created with <b>Astro</b> and <b>Sanity</b> CMS.",
    thumbnail: "/project/thumbnail/blog.webp",
    url: "https://blog.raflimalik.com",
    source: "Github",
    sourceurl: "https://github.com/RMalik777/blog",
  },
];

export const skills = [
  {
    id: 0,
    category: "Design",
    skills: [{ id: 1, name: "UI/UX" }],
  },
  {
    id: 1,
    category: "Front-End",
    skills: [
      { id: 2, name: "HTML" },
      { id: 3, name: "CSS" },
      { id: 4, name: "JavaScript" },
      { id: 5, name: "jQuery" },
      { id: 6, name: "Bootstrap" },
      { id: 7, name: "Tailwind" },
      { id: 8, name: "React.js" },
      { id: 9, name: "Next.js" },
      { id: 21, name: "Remix" },
      { id: 22, name: "Svelte" },
      { id: 23, name: "SvelteKit" },
      { id: 24, name: "Vue.js" },
      { id: 25, name: "Nuxt.js" },
      { id: 26, name: "Astro" },
      { id: 31, name: "Framer Motion" },
    ],
  },
  {
    id: 2,
    category: "Back-End",
    skills: [
      { id: 10, name: "ASP.NET" },
      { id: 19, name: "Laravel" },
    ],
  },
  {
    id: 3,
    category: "Database",
    skills: [
      { id: 11, name: "MySQL" },
      { id: 20, name: "SQLite" },
    ],
  },
  {
    id: 4,
    category: "Content Management System",
    skills: [{ id: 27, name: "Sanity" }],
  },
  {
    id: 5,
    category: "Programming",
    skills: [
      { id: 12, name: "Python" },
      { id: 13, name: "Java" },
      { id: 16, name: "C#" },
      { id: 29, name: "Rust" },
    ],
  },
  {
    id: 6,
    category: "Tools",
    skills: [
      { id: 14, name: "Adobe Premiere Pro" },
      { id: 15, name: "Adobe Photoshop" },
      { id: 17, name: "Figma" },
      { id: 30, name: "Framer" },
      { id: 18, name: "Microsoft Office" },
      { id: 28, name: "git" },
    ],
  },
];
