import './globals.css'
import Navbar from './components/navbar'
import Footer from './components/Footer'
import { DM_Sans } from 'next/font/google'

const DMS = DM_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={DMS.className}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
